# Generated by Django 3.1.5 on 2021-01-18 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Actividad comercial',
                'verbose_name_plural': 'Actividades comerciales',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('folio', models.CharField(max_length=255, verbose_name='Folio')),
                ('valid_until', models.DateField(verbose_name='Fecha de vencimiento')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='license', to='business.activity')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
            },
        ),
    ]
