# Generated by Django 3.1.5 on 2021-01-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='folio',
            field=models.CharField(max_length=255, unique=True, verbose_name='Folio'),
        ),
    ]
