# Generated by Django 3.1.5 on 2021-01-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20210120_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalregistry',
            options={'verbose_name': 'Registro de animal', 'verbose_name_plural': 'Registro de animales'},
        ),
        migrations.AddField(
            model_name='registry',
            name='identification',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Identificación'),
        ),
    ]
