# Generated by Django 3.1.5 on 2021-01-21 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20210120_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalregistry',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.animal', unique=True),
        ),
    ]
