# Generated by Django 3.1.5 on 2021-01-27 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20210120_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='license', to='business.activity'),
        ),
    ]
